# Generated by Django 3.1.7 on 2021-04-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20210420_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darknesstolight',
            options={'verbose_name_plural': 'Darkness to Light'},
        ),
        migrations.AlterModelOptions(
            name='statisticscannon',
            options={'verbose_name_plural': 'Statistics for Cannon'},
        ),
    ]
